num1 = int(input("Please enter number: "))
num2 = int(input("Please enter number: "))

print(num1 + num2)
print(num1 - num2)
print(num1 / num2)
print(num1 * num2)
print(num1 == num2)
print(num1 < num2)
print(num1 > num2)